[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración para SPA (Single Page Application)
[build]
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configuración de funciones si las tienes
[functions]
